---

- name: "Install Ansible dependencies"
  become: true
  apt:
    name: ["nodejs", "tar", "gzip"]
    state: latest
    update_cache: yes

- name: "Install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "Deploy the backend files"
  become_user: ubuntu
  unarchive:
    src: ~/backend.tgz
    dest: ~/

- name: "Start the backend service"
  become_user: ubuntu
  shell: |
    cd ~/backend
    npm i
    pm2 start npm --name backend -- start
